# Generated by Django 6.0.6 on 2026-07-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_falta'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='tipo',
            field=models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Todo el día')], default='hora', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='falta',
            name='hora',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='falta',
            name='materia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
