# Generated by Django 6.0.6 on 2026-07-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_falta_tipo_alter_falta_hora_alter_falta_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='justificada',
        ),
        migrations.AddField(
            model_name='falta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20),
        ),
    ]
