# Generated by Django 6.0.6 on 2026-07-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_falta_justificada_falta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='justificada',
            field=models.BooleanField(default=False),
        ),
    ]
