# Generated by Django 6.0.6 on 2026-07-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_falta_justificada'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='fecha_justificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falta',
            name='fecha_revision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falta',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='falta',
            name='observaciones_coordinador',
            field=models.TextField(blank=True),
        ),
    ]
