# Generated by Django 6.0.6 on 2026-07-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_falta_fecha_justificacion_falta_fecha_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='justificaciones/'),
        ),
    ]
