# Generated by Django 6.0.6 on 2026-08-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_falta_documento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='documento',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='documento',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='falta',
            name='materia',
        ),
        migrations.AddField(
            model_name='falta',
            name='hora_retiro',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='falta',
            name='motivo_retiro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='falta',
            name='quien_retiro',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='falta',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.docente'),
        ),
        migrations.AlterField(
            model_name='falta',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Registrada', 'Registrada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='falta',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='falta',
            name='tipo',
            field=models.CharField(choices=[('hora', 'Por hora'), ('dia', 'Todo el día'), ('retirada', 'Retirada')], max_length=15),
        ),
    ]
