# Generated by Django 6.1 on 2026-08-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_documento_docente_codigo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('grado', models.IntegerField(default=10)),
                ('seccion', models.CharField(default='A', max_length=5)),
            ],
            options={
                'ordering': ['grado', 'seccion'],
            },
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['curso', 'apellido', 'nombre']},
        ),
    ]
