# Generated by Django 6.1 on 2026-09-02 00:54

from django.db import migrations, models


def migrate_curso_data(apps, schema_editor):
    """Migrar datos de seccion a curso"""
    Curso = apps.get_model('core', 'Curso')
    for curso in Curso.objects.all():
        # Mapear seccion (A, B, C, etc.) a curso (01, 02, 03, etc.)
        seccion_map = {
            'A': '01', 'B': '02', 'C': '03', 'D': '04',
            'E': '05', 'F': '06', 'G': '07', 'H': '08',
        }
        # Obtener la sección del nombre (ej: "10A" -> "A")
        curso_value = seccion_map.get(curso.seccion, '01')
        curso.curso = curso_value
        curso.save()


def reverse_curso_data(apps, schema_editor):
    """Revertir migración"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_curso_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso',
            field=models.CharField(default='01', max_length=5),
        ),
        migrations.RunPython(migrate_curso_data, reverse_curso_data),
        migrations.AlterField(
            model_name='curso',
            name='grado',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='curso',
            name='seccion',
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('grado', 'curso')},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['grado', 'curso']},
        ),
    ]
