# Generated by Django 6.1.1 on 2026-09-28 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_docente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='falta',
            name='hora_hasta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='falta',
            name='quien_da_salida',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
